services:
  backend-service:
    build:
      context: ../backend
      dockerfile: Dockerfile 
    restart: unless-stopped
    ports:
      - "8000:8000"    
    networks:
      - crypto-network
  frontend-service:
    build:
      context: ../frontend
      dockerfile: Dockerfile 
    restart: unless-stopped
    ports:
      - "3000:3000"    
    depends_on:
      - backend-service
    networks:
      - crypto-network
networks:
  crypto-network:
    driver: bridge